version: '3.3'
services:
  mysql:
    image: hypriot/rpi-mysql
    #image: mysql:latest
    restart: always
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ~/workspace/docker/mysql/data:/var/lib/mysql
      - ~/workspace/docker/mysql/config:/etc/mysql/conf.d
  web:
    image: nginx
    volumns:
      - ~/my-site:/etc/nginx/conf.d/mysite.template
    ports:
      - '8080:8080'
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
  node-server:
    image: node:8
    working_dir: ~/usr/src/myapp
    volumns:
      - ~/node-app/src/app:/usr/src/myapp
    ports:
      - '3000:3000'
