version: '3.2'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_INITDB_ARGS: '--data-checksums -E utf8 --no-locale'
      POSTGRES_PASSWORD: root1234
    ports:
      - "5432:5432"    
    volumes:
      - postgres-data:/var/lib/postgresql/data          
  pg-admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "7070:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=ipawtl@hanmail.net
      - PGADMIN_DEFAULT_PASSWORD=root1234    
volumes:
  postgres-data:
  